/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.abd.personapp.view;

//import co.edu.usbbog.ing.sis.persona.controller.prototype.Dueno;
//import co.edu.usbbog.ing.sis.persona.controller.prototype.G_entrada;

import co.edu.usbbog.abd.personapp.model.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author 304
 */
public class ProductoView extends javax.swing.JPanel {

    private Principal D;

    /**
     * Creates new form Vehiculo
     */
    public ProductoView(Principal principal) {
        this.D = principal;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        campo_Nombre = new javax.swing.JTextField();
        campo_Marca = new javax.swing.JTextField();
        campo_Fecha = new javax.swing.JTextField();
        campo_costo = new javax.swing.JTextField();
        jButtonRegistrarVehiculo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPass1 = new javax.swing.JLabel();
        campo_cantidad = new javax.swing.JTextField();
        jButtonBuscar1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelName.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelName.setText("Marca");

        jLabelID.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelID.setText("Nombre");

        jLabelUser.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelUser.setText("Fecha V.");

        jLabelPass.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelPass.setText("Costo");

        campo_Nombre.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        campo_Marca.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        campo_Fecha.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        campo_costo.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N

        jButtonRegistrarVehiculo.setBackground(new java.awt.Color(0, 104, 37));
        jButtonRegistrarVehiculo.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButtonRegistrarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarVehiculo.setText("Registrar Producto");
        jButtonRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarVehiculoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 167, 82));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel5.setText("Contactanos: ");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel6.setText("Telefono: 3504734161");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel7.setText("Email: Panaderia@gmail.com");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/usbbog/ing/sis/persona/logo/logo_instagram.png"))); // NOI18N
        jLabel8.setText("@panaderia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jLabelPass1.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        jLabelPass1.setText("Cantidad");

        campo_cantidad.setFont(new java.awt.Font("Leelawadee UI", 0, 13)); // NOI18N
        campo_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cantidadActionPerformed(evt);
            }
        });

        jButtonBuscar1.setBackground(new java.awt.Color(0, 104, 37));
        jButtonBuscar1.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButtonBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar1.setText("Buscar Producto");
        jButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscar1ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 104, 37));
        jButton10.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Actualizar ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 167, 82));
        jLabel3.setText("Panaderia");

        jButton3.setBackground(new java.awt.Color(0, 104, 37));
        jButton3.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 104, 37));
        jButton4.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Ganancias");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUser)
                                    .addComponent(jLabelPass, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campo_Marca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campo_Nombre)
                                        .addComponent(campo_Fecha)
                                        .addComponent(campo_costo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(campo_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonBuscar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRegistrarVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID)
                    .addComponent(jButtonRegistrarVehiculo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campo_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelUser)
                                    .addComponent(jButton10))
                                .addGap(12, 12, 12)
                                .addComponent(jLabelPass))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campo_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelName)
                                .addComponent(jButtonBuscar1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPass1)
                            .addComponent(campo_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarVehiculoActionPerformed
        registrarProducto();
    }//GEN-LAST:event_jButtonRegistrarVehiculoActionPerformed

    private void jButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscar1ActionPerformed
        visualizarProducto();
    }//GEN-LAST:event_jButtonBuscar1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        actualizarProducto();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void campo_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cantidadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarProducto();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        visualizarGanancias();
        visualizarNomCant();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_Fecha;
    private javax.swing.JTextField campo_Marca;
    private javax.swing.JTextField campo_Nombre;
    private javax.swing.JTextField campo_cantidad;
    private javax.swing.JTextField campo_costo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscar1;
    private javax.swing.JButton jButtonRegistrarVehiculo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPass1;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void registrarProducto() {

        Producto Emp = new Producto(
                campo_Nombre.getText(),
                campo_Marca.getText(),
                campo_Fecha.getText(),
                Integer.parseInt(campo_costo.getText()),
                Integer.parseInt(campo_cantidad.getText()));
        if (D.registrarProducto(Emp)) {
            limpiar();
            JOptionPane.showMessageDialog(this, "se registro el producto");
        } else {
            JOptionPane.showMessageDialog(this, "no se registro el producto");
        }

    }

    private void actualizarProducto() {

        try {

            Producto Emp2 = new Producto(
                    campo_Nombre.getText(),
                    campo_Marca.getText(),
                    campo_Fecha.getText(),
                    Integer.parseInt(campo_costo.getText()),
                    Integer.parseInt(campo_cantidad.getText()));

            if (D.actualizarProducto(Emp2)) {
                limpiar();
                JOptionPane.showMessageDialog(this, "se actualizo el Producto");
            } else {
                JOptionPane.showMessageDialog(this, "no se actualizo el producto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los campos son obligatorios");
        }

    }

    private boolean validar() {
        if (campo_Nombre.getText().equals("")) {
            return false;
        } else if (campo_Marca.getText().equals("")) {
            return false;
        } else if (campo_Fecha.getText().equals("")) {
            return false;
        } else if (campo_costo.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }



    public void visualizarProducto() {

        try {
            String o = campo_Nombre.getText();
            D.visualizarProducto(o);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El campo de ID es obligatorio");
        }
    }

    public void visualizarGanancias(){
        D.visualizarGanancias();
    }
    
        public void visualizarNomCant(){
        D.visualizarNomCant();
    }
        
    public void eliminarProducto() {

        try {

            String o = campo_Nombre.getText();

            if (D.eliminarProducto(o)) {
                limpiar();
                JOptionPane.showMessageDialog(this, "se eliminó el producto");
            } else {
                JOptionPane.showMessageDialog(this, "no se eliminó el producto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Los campos son obligatorios");
        }
    }



    private void limpiar() {
        campo_Nombre.setText("");
        campo_Marca.setText("");
        campo_Fecha.setText("");
        campo_costo.setText("");
        campo_cantidad.setText("");

    }



}
